export const ADD_TO_CART_REQUEST = "ADD_TO_CART_REQUEST"
export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS"
export const ADD_TO_CART_FAIL = "ADD_TO_CART_FAIL"

export const GET_CART_PRODUCTS_OF_LOGIN_USER_REQUEST = "GET_CART_PRODUCTS_OF_LOGIN_USER_REQUEST"
export const GET_CART_PRODUCTS_OF_LOGIN_USER_SUCCESS = "GET_CART_PRODUCTS_OF_LOGIN_USER_SUCCESS"
export const GET_CART_PRODUCTS_OF_LOGIN_USER_FAIL = "GET_CART_PRODUCTS_OF_LOGIN_USER_FAIL"

export const REMOVE_FROM_CART_REQUEST = "REMOVE_FROM_CART_REQUEST"
export const REMOVE_FROM_CART_SUCCESS = "REMOVE_FROM_CART_SUCCESS"
export const REMOVE_FROM_CART_FAIL = "REMOVE_FROM_CART_FAIL"